ARG TARGETPLATFORM
ARG FROMPLATFORM=${TARGETPLATFORM}
ARG FROMIMAGE
FROM --platform=${FROMPLATFORM} ${FROMIMAGE}

VOLUME [ "/out" ]
WORKDIR /src/torch/pytorch

RUN python setup.py bdist_wheel && \
    python setup.py install

RUN cd build/lib.*/torch 2>/dev/null || cd build/lib/torch; \
    ln -sf _C.*.so _C.so || :; \
    ln -sf _C_flatbuffer.*.so _C_flatbuffer.so || :

CMD ["cp", "-r", "--archive", "/src/torch", "/out"]
