ARG TARGETPLATFORM
ARG FROMPLATFORM=${TARGETPLATFORM}
ARG FROMIMAGE
FROM --platform=${FROMPLATFORM} ${FROMIMAGE}

WORKDIR /src/torch/pytorch

RUN timeout --preserve-status --kill-after=330m --verbose 300m \
    python setup.py build
