name: Docker image build

on:
  push:
    branches: [ main, dev, docker ]
  pull_request:
    branches: [ main, dev, docker ]
  
env:
  DOCKERIO_USER: "${{ github.repository_owner }}"

jobs:
  first_build:
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build using Dockerfile 
      run: |
            docker buildx build --platform=linux/arm/v7 --output "type=image" --build-arg pythonlabel=3.10-bullseye --build-arg GITHUB_USER=${{ github.repository_owner }} --file ./Dockerfile .