name: pytorch-arm-build

on:
  workflow_dispatch:      # Enables the manual "Run workflow" button
  push:
    branches: [ main, dev, docker ]
  pull_request:
    branches: [ main, dev, docker ]

env:
  TORCHTAG: v2.7.1
  DOCKER_CACHE_ID: 3

jobs:
  build_pytorch_arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/arm/v7, linux/arm64/v8 ]
        pythonlabel: [ 3.10-buster, 3.11-buster, 3.9-buster ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into ghcr.io docker
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Apply ARM Patch
        run: patch -p1 < arm.patch

      - name: Build PyTorch for ARM
        run: |
          docker buildx build --platform=${{ matrix.platform }} \
            --build-arg pythonlabel=${{ matrix.pythonlabel }} \
            --build-arg GITHUB_USER=${{ github.repository_owner }} \
            --build-arg TORCHTAG=${{ env.TORCHTAG }} \
            --build-arg FROMPLATFORM=${{ matrix.platform }} \
            --tag ghcr.io/${{ github.repository_owner }}/pytorch-arm:${{ matrix.platform }}_${{ matrix.pythonlabel }}_${{ env.TORCHTAG }} \
            --file ./Dockerfile.arm .

