name: pytorch-arm-build

on:
  workflow_dispatch:
  push:
    branches: [ main, dev, docker ]
  pull_request:
    branches: [ main, dev, docker ]

env:
  TORCHTAG: v2.7.1
  DOCKER_CACHE_ID: 3

jobs:
  build_pytorch_arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/arm/v7, linux/arm64/v8 ]
        pythonlabel: [ 3.11-bullseye, 3.10-bullseye, 3.9-bullseye ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare lowercase repo owner
        run: |
          echo "LOWER_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set Docker image tag (slash to underscore)
        run: |
          echo "TAGNAME=$(echo '${{ matrix.platform }}_${{ matrix.pythonlabel }}_${{ env.TORCHTAG }}' | tr '/' '_' )" >> $GITHUB_ENV

      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ env.LOWER_OWNER }}" --password-stdin

      - name: Build PyTorch Stage 1
        run: |
          docker buildx build --platform=${{ matrix.platform }} \
            --build-arg pythonlabel=${{ matrix.pythonlabel }} \
            --build-arg GITHUB_USER=${{ env.LOWER_OWNER }} \
            --build-arg TORCHTAG=${{ env.TORCHTAG }} \
            --build-arg FROMPLATFORM=${{ matrix.platform }} \
            --tag ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage1:${{ env.TAGNAME }} \
            --file Dockerfile.stage1 .

      - name: Build PyTorch Stage 2
        run: |
          docker buildx build --platform=${{ matrix.platform }} \
            --build-arg pythonlabel=${{ matrix.pythonlabel }} \
            --build-arg GITHUB_USER=${{ env.LOWER_OWNER }} \
            --build-arg TORCHTAG=${{ env.TORCHTAG }} \
            --build-arg FROMPLATFORM=${{ matrix.platform }} \
            --build-arg FROMIMAGE=ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage1:${{ env.TAGNAME }} \
            --tag ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage2:${{ env.TAGNAME }} \
            --file Dockerfile.stage2 .

      - name: Build PyTorch Stage 3
        run: |
          docker buildx build --platform=${{ matrix.platform }} \
            --build-arg pythonlabel=${{ matrix.pythonlabel }} \
            --build-arg GITHUB_USER=${{ env.LOWER_OWNER }} \
            --build-arg TORCHTAG=${{ env.TORCHTAG }} \
            --build-arg FROMPLATFORM=${{ matrix.platform }} \
            --build-arg FROMIMAGE=ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage2:${{ env.TAGNAME }} \
            --tag ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage3:${{ env.TAGNAME }} \
            --file Dockerfile.stage3 .

      - name: Build PyTorch Stage 4
        run: |
          docker buildx build --platform=${{ matrix.platform }} \
            --build-arg pythonlabel=${{ matrix.pythonlabel }} \
            --build-arg GITHUB_USER=${{ env.LOWER_OWNER }} \
            --build-arg TORCHTAG=${{ env.TORCHTAG }} \
            --build-arg FROMPLATFORM=${{ matrix.platform }} \
            --build-arg FROMIMAGE=ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage3:${{ env.TAGNAME }} \
            --tag ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage4:${{ env.TAGNAME }} \
            --file Dockerfile.stage4 .

      - name: Build PyTorch Stage 5
        run: |
          docker buildx build --platform=${{ matrix.platform }} \
            --build-arg pythonlabel=${{ matrix.pythonlabel }} \
            --build-arg GITHUB_USER=${{ env.LOWER_OWNER }} \
            --build-arg TORCHTAG=${{ env.TORCHTAG }} \
            --build-arg FROMPLATFORM=${{ matrix.platform }} \
            --build-arg FROMIMAGE=ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage4:${{ env.TAGNAME }} \
            --tag ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage5:${{ env.TAGNAME }} \
            --file Dockerfile.stage5 .

      - name: Build PyTorch Stage 6
        run: |
          docker buildx build --platform=${{ matrix.platform }} \
            --build-arg pythonlabel=${{ matrix.pythonlabel }} \
            --build-arg GITHUB_USER=${{ env.LOWER_OWNER }} \
            --build-arg TORCHTAG=${{ env.TORCHTAG }} \
            --build-arg FROMPLATFORM=${{ matrix.platform }} \
            --build-arg FROMIMAGE=ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage5:${{ env.TAGNAME }} \
            --tag ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage6:${{ env.TAGNAME }} \
            --file Dockerfile.stage6 .

      - name: Build PyTorch Stage 7
        run: |
          docker buildx build --platform=${{ matrix.platform }} \
            --build-arg pythonlabel=${{ matrix.pythonlabel }} \
            --build-arg GITHUB_USER=${{ env.LOWER_OWNER }} \
            --build-arg TORCHTAG=${{ env.TORCHTAG }} \
            --build-arg FROMPLATFORM=${{ matrix.platform }} \
            --build-arg FROMIMAGE=ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage6:${{ env.TAGNAME }} \
            --tag ghcr.io/${{ env.LOWER_OWNER }}/pytorch-arm/stage7:${{ env.TAGNAME }} \
            --file Dockerfile.stage7 .
